name: Build & Release SeaLight_Studio

on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12.3"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          python -OO -m PyInstaller src/main.py \
          --optimize 2\
          --clean\
          --onefile\
          --noconsole\
          --name SeaLight_Studio\
          --icon icon.ico\
          --add-data icon.ico:image/.\
        if: runner.os == 'Windows'

      - name: Build with PyInstaller
        run: |
          python3 -OO -m PyInstaller src/main.py\
          --strip\
          --optimize 2\
          --clean -F\
          --noconsole\
          --name SeaLight_Studio\
          --icon icon/icon.ico\
        if: runner.os != 'Windows'

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.os }}-SeaLight_Studio
          path: dist/*.exe
          if: runner.os == 'Windows'

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.os }}-SeaLight_Studio
          path: dist/*
          if: runner.os != 'Windows'

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Voici les ex√©cutables pour SeaLight_Studio ${{ github.ref_name }}.
            - Windows : `SeaLight_Studio.exe`
            - Linux : `SeaLight_Studio`
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ubuntu-latest-SeaLight_Studio/SeaLight_Studio
          asset_name: SeaLight_Studio_Linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-latest-SeaLight_Studio/SeaLight_Studio.exe
          asset_name: SeaLight_Studio_Windows.exe
          asset_content_type: application/octet-stream
